#!/bin/sh

if ! [ "$SRV_DOMAIN" ]; then
	>&2 echo "Error: Missing required environment variables!"
	exit 1
fi

if [ $# -eq 0 ]; then
	client_name="client_$RANDOM"
	client_csr="$(openssl req -newkey rsa:4096 -nodes -subj "/CN=$client_name" -keyout $client_name)"
	client_key="$(cat $client_name)"
	rm $client_name
else if [ $# -eq 1 ]; then
	client_csr="$1"
	client_key="YOUR PRIVATE KEY GOES HERE"
else
	>&2 echo "Error: Unexpected arguments!"
	exit 1
fi

cd /etc/openvpn

ca_cert="$(cat ca.crt)"
client_cert="$(echo "$client_csr" | openssl x509 -req -days 3650 -sha256 -CA ca.crt -CAkey ca.key -CAcreateserial 2>/dev/null)"
if [ $? -ne 0 ]; then
	2>&1 echo "Error: Failed to sign certificate!"
	exit 1
fi

printf "client
remote vpn.$SRV_DOMAIN 1194 udp
dev tun

cipher AES-256-CBC
data-ciphers AES-256-CBC

persist-key
persist-tun

nobind

# TODO: server.crt keyUsage set to 'digitalSignature, keyEncipherment' and extendedKeyUsage to 'serverAuth'
# remote-cert-tls server

<ca>
$ca_cert
</ca>

<cert>
$client_cert
</cert>

<key>
$client_key
</key>
"
