version: 3
name: septs
services:
  d3rp:
    build: https://src.h8c.de/d3rp/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/letsencrypt
    env_file:
      - ./config.env
  src:
    build: https://src.h8c.de/src.h8c.de/
    restart: unless-stopped
    volumes:
      - ./data/git:/git
  www:
    build: https://src.h8c.de/h8c.de/
    restart: unless-stopped
    # TODO: temporary
    stop_signal: SIGKILL
