version: "3"
name: septs
services:
  d3rp:
    build: https://src.h8c.de/d3rp.git#main
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/letsencrypt
    environment:
      SUBDOMAINS: reg,src,tnds
    env_file:
      - ./config.env
  reg:
    image: registry:2
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./data/reg/registry:/var/lib/registry
      - ./data/reg/auth:/auth
  src:
    build: https://src.h8c.de/src.h8c.de.git#main
    restart: unless-stopped
    volumes:
      - ./data/git:/git
  www:
    build: https://src.h8c.de/h8c.de.git#main
    restart: unless-stopped
    # TODO: temporary
    stop_signal: SIGKILL
  tnds:
    build: https://src.h8c.de/tnds.git#main
    restart: unless-stopped
