#!/bin/sh

if ! [ "$CF_API_TOKEN" -a "$SRV_DOMAIN" -a "$SRV_EMAIL" ]; then
	>&2 echo "Error: Missing required environment variables!"
	exit 1
fi

trap "echo 'Stopping...'; exit" 15

echo "dns_cloudflare_api_token = $CF_API_TOKEN" > "/cf.ini"
chmod go-rwx "/cf.ini"

echo "Checking for valid SSL certificates..."
certbot renew --quiet --cert-name site
if [ $? -ne 0 ]; then
	echo "Missing valid SSL certificates, registering new domain..."
	certbot certonly \
		--non-interactive \
		--agree-tos \
		--cert-name site \
		--email "$SRV_EMAIL" \
		--domains "$SRV_DOMAIN,*.$SRV_DOMAIN" \
		--dns-cloudflare \
		--dns-cloudflare-credentials "/cf.ini" \
		--dns-cloudflare-propagation-seconds "60"
	if [ $? -ne 0 ]; then
		>&2 echo "Error: Failed to register domain!"
		exit 1
	fi
fi

DAY="$(shuf -i 0-6 -n 1)"
HOUR="$(shuf -i 0-23 -n 1)"
MINUTE="$(shuf -i 0-59 -n 1)"
echo "$MINUTE $HOUR * * $DAY root certbot renew --quiet --cert-name site" >> /var/spool/cron/crontabs/root

echo "Success. Checking for renewals every week at ${DAY}d ${HOUR}h ${MINUTE}m"

crond -f &
wait $!
