#!/bin/sh

if ! [ "$CF_API_TOKEN" -a "$CF_ZONE" -a \( "$CF_A_RECORD" -o "$CF_AAAA_RECORD" \) ]; then
	>&2 echo "Error: Missing required environment variables!"
	exit 1
fi

trap "echo 'Stopping...'; exit" 15

current_ipv4=""
current_ipv6=""

while true; do

	new_ipv4="$(curl --silent ipv4.icanhazip.com)"
	if [ "$CF_A_RECORD" -a -n "$new_ipv4" -a "$new_ipv4" != "$current_ipv4" ]; then
		echo "New public IPv4: $new_ipv4"
		curl --silent \
			--request PATCH "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/dns_records/$CF_A_RECORD" \
			--header "Authorization: Bearer $CF_API_TOKEN" \
			--header "Content-Type: application/json" \
			--data '{"content":"'"$new_ipv4"'"}' |
			jq --exit-status ".success" >/dev/null &&
			current_ipv4="$new_ipv4" ||
			>&2 echo "Error: Failed to update A record!"
	fi

	new_ipv6="$(curl --silent ipv6.icanhazip.com)"
	if [ "$CF_AAAA_RECORD" -a -n "$new_ipv6" -a "$new_ipv6" != "$current_ipv6" ]; then
		echo "New public IPv6: $new_ipv6"
		curl --silent \
			--request PATCH "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/dns_records/$CF_AAAA_RECORD" \
			--header "Authorization: Bearer $CF_API_TOKEN" \
			--header "Content-Type: application/json" \
			--data '{"content":"'"$new_ipv6"'"}' |
			jq --exit-status ".success" >/dev/null &&
			current_ipv6="$new_ipv6" ||
			>&2 echo "Error: Failed to update AAAA record!"
	fi

	sleep 300 &
	wait $!
done
